run_flask_app:
  stage: test
  image: python:3.8
  script:
    - pip install -r flask_admin_example/requirements.txt
    - cd flask_admin_example
    - flask run
  only:
    - master
  tags:
    - docker
  variables:
    FLASK_ENV: development
    FLASK_APP: app.py
    FLASK_RUN_PORT: 5000
    FLASK_RUN_HOST: "0.0.0.0"
    FLASK_RUN_DEBUG: 1
